number_of_generated_records: 1000000
attributes_list:
  - ColumnName: key
    Generator: key_generator
    DataDescriptor:
      Prefix: PKey_
      LeadingZeros: 7
  - ColumnName: ParentKey
    Generator: child_key_generator
    DataDescriptor:
      Prefix: PKey_
      LeadingZeros: 7
      ChildCountPerSublevel:
        - 100
        - 100
        - 100
  - ColumnName: salary
    Generator: float_generator
    DataDescriptor:
      Expression: rand(42) * 3000
  - ColumnName: Name1
    Generator: string_generator
    DataDescriptor:
      Values:
        - value1
        - Value2
        - Value3
  - ColumnName: Name_rand
    Generator: string_generator
    DataDescriptor:
      Random: 'True'
      NumChar: 8
  - ColumnName: Name_rand2
    Generator: string_generator
    DataDescriptor:
      Pattern: ^X8#__#^N2#@#^A4#.#^A3
  - ColumnName: open_date
    Generator: date_generator
    DataDescriptor:
      StartDate: 01/02/2001
      EndDate: 01/03/2003
  - ColumnName: close_date
    Generator: close_date_generator
    DataDescriptor:
      StartDateColumnName: open_date
      CloseDateRangeInDays: 20
  - ColumnName: phone_number
    Generator: string_generator
    DataDescriptor:
      Pattern: ^N8
target_list:
  - target: Dynamodb
    attributes:
      dynamodb.output.tableName: TDG_demo_v6
      dynamodb.throughput.write.percent: '1.0'
